# Generated by Django 5.2 on 2025-05-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phonenum',
            field=models.TextField(null=True),
        ),
    ]
