# Generated by Django 5.2 on 2025-05-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_phonenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenum',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
