# Generated by Django 5.1.7 on 2025-05-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='generation',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Babylion'), (2, 'Manager')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='part',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Plan'), (2, 'Design'), (3, 'Frontend'), (4, 'Backend'), (5, 'Ai')], null=True),
        ),
    ]
