# Generated by Django 5.2 on 2025-05-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='major',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='semester',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
