# Generated by Django 5.1.7 on 2025-05-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='hashtag',
            field=models.ManyToManyField(blank=True, null=True, to='community.hashtag'),
        ),
        migrations.AlterField(
            model_name='question',
            name='hashtag',
            field=models.ManyToManyField(blank=True, null=True, to='community.hashtag'),
        ),
    ]
