# Generated by Django 5.2 on 2025-04-15 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='upload_time',
        ),
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='username',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='community',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='community',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
