# Generated by Django 5.2 on 2025-04-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(),
        ),
    ]
