# Generated by Django 5.2 on 2025-04-13 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_comment_comment_q'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_q',
            name='post',
        ),
        migrations.AddField(
            model_name='comment_q',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_Q', to='community.question'),
        ),
    ]
