# Generated by Django 5.2 on 2025-04-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='hashtag',
            field=models.ManyToManyField(to='community.hashtag'),
        ),
        migrations.AddField(
            model_name='question',
            name='hashtag',
            field=models.ManyToManyField(to='community.hashtag'),
        ),
    ]
