# Generated by Django 5.2 on 2025-04-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_hashtag_question_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
