# Generated by Django 5.2 on 2025-04-13 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_remove_comment_q_post_comment_q_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_q',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments_Q', to='community.question'),
            preserve_default=False,
        ),
    ]
