# Generated by Django 5.2 on 2025-04-13 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_comment_q_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_q',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_Q', to='community.question'),
        ),
    ]
