# Generated by Django 5.2 on 2025-05-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_question_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='username',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
