# Generated by Django 5.2 on 2025-04-13 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_comment_q_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment_Q',
        ),
    ]
