# Generated by Django 5.2 on 2025-05-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_commentforpost_commentforquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentforquestion',
            old_name='post',
            new_name='question',
        ),
    ]
