# Generated by Django 5.2 on 2025-05-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
