# Generated by Django 5.2 on 2025-05-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_post_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
