# Generated by Django 5.2 on 2025-05-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
    ]
