# Generated by Django 5.2.1 on 2025-05-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='hashtag',
            field=models.ManyToManyField(to='forums.hashtag'),
        ),
        migrations.AlterField(
            model_name='question',
            name='hashtag',
            field=models.ManyToManyField(to='forums.hashtag'),
        ),
    ]
